### ISSUE TITLE
Placing contracts across directories fails to produce ABI

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-pm#231] opened 2016-10-05 19:04 UTC
This was briefly discussed with @VoR0220 and it might be an CLI issue. But since the behavior for the user appears when using EPM, I'm creating the issue here first.

The [tests.zip](https://github.com/eris-ltd/eris-pm/files/512097/tests.zip) contains two directories "1" and "2", each with a similar setup. However in 1 the main .sol unit test file is located in the same directory as the epm.yaml and this setup works. In 2 the .sol file is placed in a `test/` subfolder such that references to other contracts start with `../contracts/`. Running the epm.yaml in folder "2" fails to produce the ABI and results in failure:

```
$ eris pkgs do -c test5 -a 6FD2036A9C4466A12640899B806C6F8420A8B01A -l http://172.17.0.4:9099
Performing action. This can sometimes take a wee while
Executing Job                                 defaultAddr
Executing Job                                 DocumentTest
Executing Job                                 testDocumentCreation
ABI Error                                 abi=
                                         data=
                                         dest=
                                       rawErr=Abi doesn't exist for =>	abi

There has been an error in finding or in using your ABI. ABI's are "Application Binary
Interface" and they are what let us know how to talk to smart contracts.

These little json files can be read by a variety of things which need to talk to smart
contracts so they are quite necessary to be able to find and use properly.

The ABIs are saved after the deploy events. So if there was a glitch in the matrix,
we apologize in advance.

The marmot recovery checklist is...
  * ensure your chain is running and you have enough validators online
  * ensure that your contracts successfully deployed
  * if you used imports or have multiple contracts in one file check the instance
    variable in the deploy and the abi variable in the call/query-contract
  * make sure you're calling or querying the right function
  * make sure you're using the correct variables for job results
```

Versions:
```
OSX version: 10.11.6
Eris CLI Version: 0.12.0
Docker:
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
docker-machine version 0.7.0, build a650a40
```

**Comment by jasonklein** [comment] 2016-10-07 17:11
@j-h-scheufen: is the related to #146 or #202? (or perhaps they are all related). Either way, when I set instance in the `2/epm.yaml`, to `all` or `DocumentTest`, epm runs as intended.

**Comment by compleatang** [comment] 2016-10-13 02:46
Closing here. Please log a new ticket in cli's repo if this re-arises.

**Closed by compleatang** 2016-10-13 02:46 UTC
Labels: bug
