### ISSUE TITLE
address parameters always 0

### ISSUE THREAD

**Issue by arrivets** [eris-ltd/eris-pm#32] opened 2015-12-09 11:26 UTC
Hello,

whenever I use epm to call a contract method that takes a parameter of type address, the parameter in the call-data is always set to 0.

For example, here is the contract I am trying to test with epm:
```
contract IdisContractsFTW {
  address storedAddress;

  function set(address x) {
    storedAddress = x;
  }

  function get() constant returns (address retVal) {
    return storedAddress;
  }

}
```
and the epm.yaml:

```
jobs:

- name: account
  job:
    account:
      address: 3F1861698CE1EC9DED051754AB211D6523637B4F

- name: setStorage
  job:
    set:
      val: 666661698CE1EC9DED051754AB211D6523637B4F

- name: deployStorageK
  job:
    deploy:
      contract: idi.sol
      wait: true

- name: setStorage
  job:
    call:
      destination: $deployStorageK
      data: set $setStorage
      wait: true

- name: queryStorage
  job:
    query-contract:
      destination: $deployStorageK
      data: get

- name: assertStorage
  job:
    assert:
      key: $queryStorage
      relation: eq
      val: $setStorage
```

And here is what the epm logs say for the setStorage job:
```
Executing Job Named =>		setStorage
	Type =>			Call
Fixing Variables =>		$deployStorageK:38EA42CE0F563DAC06301D859C2CBF0432238039
ABI Spec =>			{map[get:get() set:set(address)]}
Fixing Variables =>		$setStorage:666661698CE1EC9DED051754AB211D6523637B4F
Calling =>			38EA42CE0F563DAC06301D859C2CBF0432238039:2801617e0000000000000000000000000000000000000000000000000000000000000000
```

So the address parameter is always set to 0000000000000000000000000000000000000000000000000000000000000000 although I provided something else. This happens also when the parameter is specified directly ( as opposed to through a variable) 

Is there a special way to use parameters of type address?

Thanks

**Comment by compleatang** [comment] 2015-12-09 11:31
Thanks for the report. That looks like a bug to me. Definitely not expected behaviour. 

I will look into this now, but one thing you may want to do is to change the second `setStorage` job name to something else. That *should not* affect the behaviour as the variables only get "sunk" after the job completes rather than before.

**Comment by arrivets** [comment] 2015-12-09 11:58
thanks

**Comment by compleatang** [comment] 2015-12-09 11:59
OK. Have isolated the issue, EPM is not (yet) very smart with structuring types. If you add `0x` before the address then it will encoding it properly. But the deploy command will still fail because it decodes as `000000000000000000000000666661698CE1EC9DED051754AB211D6523637B4F`.

I'll work up a fix for this today I hope.

**Comment by compleatang** [comment] 2015-12-10 01:26
@arrivets Thanks for that bug report! It required some deep digging within a few packages but I think we've got it all sorted now. Just waiting for tests to pass then it should be good to go.

**Closed** 2015-12-11 04:35 UTC
Labels: bug

**Comment by compleatang** [comment] 2015-12-11 04:37
@arrivets this should be sorted now. In about 20 minutes you can do a `docker pull quay.io/eris/epm:0.11.0` and then everything should be sorted for you to work with addresses. We've added tests for these now too so should not be a problem going forward.

**Comment by arrivets** [comment] 2015-12-11 14:09
Yep that s working. Thanks for the prompt reaction.
